In [3]:
#Data Reading Tasks
#Read the dataset from a CSV file into a pandas DataFrame.
import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()

Saving sales.csv to sales.csv

In [19]:
print(df)

     OrderID       date region   product     category customer_type  quantity  \
0          1 2024-04-12   East    Laptop  Electronics     Returning         8
1          2 2024-12-14  South   Monitor  Accessories     Returning         2
2          3 2024-09-27  North     Phone  Accessories           New         5
3          4 2024-04-16   West     Mouse  Electronics     Returning         1
4          5 2024-03-12   West     Phone  Electronics     Returning         7
..       ...        ...    ...       ...          ...           ...       ...
495      496 2024-11-20  South     Mouse  Accessories     Returning         6
496      497 2024-01-04  North     Phone  Accessories     Returning         9
497      498 2024-01-16  South  Keyboard  Electronics     Returning         6
498      499 2024-10-06  North     Phone  Accessories     Returning         2
499      500 2024-12-01  North   Monitor  Electronics           New         2

     price  discount    sales
0      590      0.09  4295.20
1      262      0.18   429.68
2      512      0.09  2329.60
3      485      0.09   441.35
4      332      0.22  1812.72
..     ...       ...      ...
495    314      0.23  1450.68
496    369      0.23  2557.17
497    722      0.14  3725.52
498   1449      0.12  2550.24
499    869      0.09  1581.58

[500 rows x 10 columns]

In [5]:
import pandas as pd

df = pd.read_csv("sales.csv")
df.head()

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72

In [6]:
#Display the first 8 rows and check the basic structure of the dataset using .info()
df.head(8)

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
5,6,2024-07-07,West,Laptop,Electronics,New,8,1480,0.01,11721.60
6,7,2024-01-21,East,Mouse,Accessories,Returning,6,137,0.27,600.06
7,8,2024-04-12,West,Phone,Accessories,Returning,5,1117,0.26,4132.90

In [8]:
#Basic Structure of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    object
 2   region         500 non-null    object
 3   product        500 non-null    object
 4   category       500 non-null    object
 5   customer_type  500 non-null    object
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), object(5)
memory usage: 39.2+ KB

In [7]:
#Get statistical summary of numerical columns using .describe()
df.describe()

         order_id    quantity        price   discount         sales
count  500.000000  500.000000   500.000000  500.00000    500.000000
mean   250.500000    4.968000   768.158000    0.14666   3333.059560
std    144.481833    2.569081   404.010497    0.08612   2693.185995
min      1.000000    1.000000    50.000000    0.00000     67.320000
25%    125.750000    3.000000   432.750000    0.08000   1120.867500
50%    250.500000    5.000000   742.000000    0.15000   2582.805000
75%    375.250000    7.000000  1094.500000    0.22000   4998.030000
max    500.000000    9.000000  1499.000000    0.30000  12700.800000

In [9]:
#Check Column Name
df.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales'],
      dtype='object')

In [10]:
#Rename Column
df.rename(columns={"order_id": "OrderID"}, inplace=True)

In [11]:
#Data Cleaning Task
#Check Missing Values
df.isnull().sum()

OrderID          0
date             0
region           0
product          0
category         0
customer_type    0
quantity         0
price            0
discount         0
sales            0
dtype: int64

In [15]:
#Handle Missing Values
df["price"].fillna(df["price"].mean(), inplace=True)

/tmp/ipykernel_813/2539935628.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["price"].fillna(df["price"].mean(), inplace=True)

In [16]:
#Check Duplicates
df.duplicated().sum()

np.int64(0)

In [17]:
#Remove Duplicates
df.drop_duplicates(inplace=True)

In [18]:
#Convert Date Column to datatime
df["date"] = pd.to_datetime(df["date"])

In [21]:
#Checks Datatypes
df.dtypes

OrderID                   int64
date             datetime64[ns]
region                   object
product                  object
category                 object
customer_type            object
quantity                  int64
price                     int64
discount                float64
sales                   float64
dtype: object

In [23]:
#Check data types of all columns and convert if necessary (e.g., ensure 'quantity' is int, price in float
df["quantity"] = df["quantity"].astype(int)

df["price"] = df["price"].astype(float)

In [28]:
#Standardized Region Values
df["region"] = df["region"].str.strip().str.title()

In [29]:
#DATA ANALYSIS TASKS
#Total sales by region
df["sales"] = df["quantity"] * df["price"]
sales_by_region = df.groupby("region")["sales"].sum()

print(sales_by_region)

region
East     490986.0
North    607227.0
South    418989.0
West     433493.0
Name: sales, dtype: float64

In [30]:
#Region with Highest sales
sales_by_region.idxmax()

'North'

In [31]:
#Average Discount by product category
df.groupby("category")["discount"].mean()

category
Accessories    0.151111
Electronics    0.142744
Name: discount, dtype: float64

In [39]:
#top five products by quantity sold
df.groupby("product")["quantity"].sum().sort_values(ascending=False).head(5)

product
Mouse       481
Laptop      449
Tablet      411
Keyboard    390
Phone       383
Name: quantity, dtype: int64

In [40]:
#Monthly Sales Trend
df["month"] = df["date"].dt.month
df.groupby("month")["sales"].sum()

month
1     112836.0
2     153666.0
3      84870.0
4     176085.0
5     212126.0
6     182172.0
7     148403.0
8     228714.0
9     188593.0
10    150810.0
11    138532.0
12    173888.0
Name: sales, dtype: float64

In [41]:
#Discount impact on sales
df.groupby(df["discount"] > 0)["sales"].mean()

discount
False    4165.846154
True     3894.330595
Name: sales, dtype: float64

In [42]:
#Customer Behaviour
df.groupby("customer_type")[["quantity","sales"]].mean()

               quantity        sales
customer_type
New            4.937238  3869.389121
Returning      4.996169  3930.693487