In [1]:
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving student_data_clean.csv to student_data_clean.csv

In [2]:
import pandas as pd

df = pd.read_csv("student_data_clean.csv")

In [3]:
print(df)

      Student_ID        Name  Age  Gender Department  Semester  CGPA  \
0           1001   Student_0   24   Other       Math         3   NaN
1           1002   Student_1   21  Female         EE         1  3.94
2           1003   Student_2   22   Other         EE         5  2.44
3           1004   Student_3   24    Male         EE         4  3.47
4           1005   Student_4   20    Male         CS         2  3.53
...          ...         ...  ...     ...        ...       ...   ...
1025        1026  Student_25   18   Other       Math         8  2.01
1026        1027  Student_26   21   Other        BBA         6  3.87
1027        1028  Student_27   19  Female       Math         1  3.64
1028        1029  Student_28   23    Male         EE         5  3.62
1029        1030  Student_29   22   Other       Math         2  3.77

      Attendance_Rate  Scholarship Admission_Date  Midterm_Marks  Final_Marks  \
0                61.0        False     2021-09-11             26           33
1                98.0        False     2020-01-26              0           39
2                66.0        False     2022-08-14             20           46
3                91.0        False     2021-02-24             19           14
4                79.0        False     2021-10-24             12           10
...               ...          ...            ...            ...          ...
1025             89.0        False     2022-05-23              3           17
1026             57.0        False     2021-02-12             15           13
1027             89.0        False     2020-10-26              7           17
1028             93.0         True     2022-06-26             15           27
1029             72.0        False     2021-08-24             26           23

            City  Study_Hours_Per_Day    Fees_Paid
0         Multan                   10          NaN
1         Lahore                    5  Installment
2     Faisalabad                    7         Full
3     Faisalabad                    8         Full
4        Karachi                    3  Installment
...          ...                  ...          ...
1025      Multan                    9  Installment
1026     Karachi                    8         Full
1027   Islamabad                    8  Installment
1028   Islamabad                    5      Pending
1029   Islamabad                    9         Full

[1030 rows x 15 columns]

In [4]:
#average study hours by Department
df.groupby('Department')['Study_Hours_Per_Day'].mean()

Department
BBA        6.309179
CS         5.752525
EE         6.308989
Math       5.936170
Physics    6.042453
Name: Study_Hours_Per_Day, dtype: float64

In [6]:
#  Maximum CGPA in Each Department
# Har Department ka highest CGPA find karo.
df.groupby('Department')['CGPA'].max()

Department
BBA        3.99
CS         3.98
EE         3.98
Math       4.00
Physics    4.00
Name: CGPA, dtype: float64

In [7]:
# Total Students in Each Semester
# Har Semester me kitne students hain?

df['Semester'].value_counts()

Semester
3    145
4    140
1    137
5    131
8    124
6    123
7    121
2    109
Name: count, dtype: int64

In [12]:
# create pivot table
pivot_table = pd.pivot_table(df,
                             index="Department",
                             columns="Semester",
                             aggfunc="count")

pivot_table

           Admission_Date                             Age      ... Student_ID  \
Semester                1   2   3   4   5   6   7   8   1   2  ...          7
Department                                                     ...
BBA                    27  19  33  26  30  20  23  29  27  19  ...         23
CS                     29  25  17  29  29  26  22  21  29  25  ...         22
EE                     25   9  21  26  25  19  23  30  25   9  ...         23
Math                   33  25  37  33  24  26  28  29  33  25  ...         28
Physics                23  31  37  26  23  32  25  15  23  31  ...         25

               Study_Hours_Per_Day
Semester     8                   1   2   3   4   5   6   7   8
Department
BBA         29                  27  19  33  26  30  20  23  29
CS          21                  29  25  17  29  29  26  22  21
EE          30                  25   9  21  26  25  19  23  30
Math        29                  33  25  37  33  24  26  28  29
Physics     15                  23  31  37  26  23  32  25  15

[5 rows x 104 columns]

In [11]:
# Pivot table with CGPA mean
pivot_table = pd.pivot_table(df,
                             values="CGPA",
                             index="Department",
                             columns="Semester",
                             aggfunc="mean")

pivot_table

Semester,1,2,3,4,5,6,7,8
Department,,,,,,,,
BBA,2.932000,2.874211,3.131562,2.995217,2.933793,2.987895,3.233913,3.161786
CS,3.179615,3.050800,3.093529,3.328276,2.920357,3.016400,2.984286,2.943158
EE,3.035909,2.776667,3.176000,3.029200,3.106250,3.271875,2.977727,2.965185
Math,3.172813,2.971250,2.963636,3.131935,2.926957,3.013077,3.140741,3.011786
Physics,3.018571,3.032333,2.984857,2.971739,2.909545,3.098065,3.087200,3.104000

In [42]:
# Attendence calculate with semester
pivot_attendance = pd.pivot_table(df,
                                  values="Attendance_Rate",
                                  index="Department",
                                  columns="Gender",
                                  aggfunc='sum')
# percentage mein convert
pivot_attendance = (pivot_attendance * 100).round(0)
pivot_attendance

Gender        Female      Male     Other
Department
BBA         480500.0  571300.0  440200.0
CS          436200.0  431700.0  535200.0
EE          456900.0  460000.0  401000.0
Math        587100.0  471800.0  646500.0
Physics     517400.0  544300.0  485800.0

In [ ]:
pivot_attendance = pd.pivot_table(df,
                                  values="Attendance_Rate",
                                  index="Department",
                                  columns="Gender",
                                  aggfunc="mean")

# percentage mein convert
pivot_attendance = pivot_attendance * 100

pivot_attendance

In [15]:
# Students with Attendance Above 90%
# Un students ka data show karo jinki Attendance_Rate > 90 hai.
df['Attendance_Rate'] > 90

0       False
1        True
2       False
3        True
4       False
        ...
1025    False
1026    False
1027    False
1028     True
1029    False
Name: Attendance_Rate, Length: 1030, dtype: bool

In [18]:
# Average Midterm Marks by Gender
# Male vs Female students ke average Midterm_Marks compare karo.
df.groupby('Gender')['Midterm_Marks'].mean()

Gender
Female    15.433234
Male      14.205202
Other     14.913545
Name: Midterm_Marks, dtype: float64

In [30]:
# Average Final Marks of Scholarship Students
df[df['Scholarship']=='Yes']['Final_Marks'].mean()

nan

In [31]:
# Count of Students by Gender
df['Gender'].value_counts()

Gender
Other     347
Male      346
Female    337
Name: count, dtype: int64